annotations:
  tkeel.io/deployment-name: console-plugin-tenant-data-subscription
  tkeel.io/enable: 'true'
  tkeel.io/plugin-port: '80'
  tkeel.io/tag: manager
  tkeel.io/version: v0.4.0
apiVersion: v2
appVersion: 0.4.0-alpha.2
description: 前端租户平台的「数据订阅」插件
maintainers:
  - email: caoyue@yunify.com
    name: caoyue
name: console-plugin-tenant-data-subscription
type: application
version: 0.4.3
